@logterms
Feature: Login to the Portal

  Scenario Outline: open portal.heyprimo
    Given the user opens the Portal site
    When the user logs in with "<email>" and "<password>"
    Then I should see the tittle "PRIMO"

    Examples:
      | email                                         | password           |
      | andrea@a1fsinc.com                            | A1$2026            |
      | rbuendia@a1fsinc.com                          | A1$2026            |
      | abba@abbatransusa.com                         | ABBA$2026          |
      | jeffrey.tsai@agslogistics.com                 | ACCELERATED$2026   |
      | michael.julao@agslogistics.com                | ACCELERATED$2026   |
      | senita.salkic@agslogistics.com                | ACCELERATED$2026   |
      | victor.szeto@agslogistics.com                 | ACCELERATED$2026   |
      |                          2box@actscrating.com | ACTS$2026          |
      | dchen@adpgl.com                               | ADP$2026           |
      | jdonovan@adpgl.com                            | ADP$2026           |
      | jhui@adpgl.com                                | ADP$2026           |
      | mlopez@adpgl.com                              | ADP$2026           |
      | jaychoi@aif-usa.com                           | ADVANCED$2026      |
      | jfkae@omnilogistics.com                       | AIR$2026           |
      | john.lee@airpower-chi.com                     | AIR$2026           |
      | laura.oshea@airpower-chi.com                  | AIR$2026           |
      | lily.queriones@airpower-chi.com               | AIR$2026           |
      | vince.garcia@airpower-chi.com                 | AIR$2026           |
      | vzhang@airseachicago.com                      | AIR$2026           |
      | gmladzhova@airseachicago.com                  | AIR$2026           |
      | h.li@airseachicago.com                        | AIR$2026           |
      | kcontreras@airseachicago.com                  | AIR$2026           |
      | lxu@airseachicago.com                         | AIR$2026           |
      | peri@airseachicago.com                        | AIR$2026           |
      | cwang@airseachicago.com                       | AIR$2026           |
      | zhou@airseachicago.com                        | AIR$2026           |
      | chris@sar-logistics.com                       | AIRCON$2026        |
      | jcondon@airconai.com                          | AIRCON$2026        |
      | cnicolo@airtrukseatruk.com                    | AIRTRUK$2026       |
      | ae@alliance.com                               | ALLIANCE$2026      |
      | aiexports@alliance.com                        | ALLIANCE$2026      |
      | lmoore@alliance.com                           | ALLIANCE$2026      |
      | tim@allisonshipping.com                       | ALLISON$2026       |
      | jacob@allisonshipping.com                     | ALLISON$2026       |
      | jericho@allisonshipping.com                   | ALLISON$2026       |
      | anjelie@allpointsunlimited.com                | ALLPOINTS$2026     |
      | john.granato@alpiusa.com                      | ALPI$2026          |
      | valentin.shafarenko@alpiusa.com               | ALPI$2026          |
      | ilse.alvarez@alpiusa.com                      | ALPI$2026          |
      | michael.tse@altiaglobal.com                   | ALTIA$2026         |
      | airops@altiaglobal.com                        | ALTIA$2026         |
      | bos7@altiaglobal.com                          | ALTIA$2026         |
      | john@ancexpr.com                              | ANC$2026           |
      | dispatch-dfw@apexglobe.com                    | APEX$2026          |
      | airexport-ord@apexglobe.com                   | APEX$2026          |
      | air-ord@apexglobe.com                         | APEX$2026          |
      | jiajun.guan@apexglobe.com                     | APEX$2026          |
      | anthony.mendivel@apexglobe.com                | APEX$2026          |
      | jimmy.wang@apexglobe.com                      | APEX$2026          |
      | kimberly.mathias@apexglobe.com                | APEX$2026          |
      | dispatch-jfk@apexglobe.com                    | APEX$2026          |
      | glen.kim@apexglobe.com                        | APEX$2026          |
      | jfk-dispatch@apexglobe.com                    | APEX$2026          |
      | michael.yang@apexglobe.com                    | APEX$2026          |
      | tomh@apexglobe.com                            | APEX$2026          |
      | licao@arcduetgroupus.com                      | ARC$2026           |
      | accounting@argents.com                        | ARGENTS$2026       |
      | airexport@argents.com                         | ARGENTS$2026       |
      | customersupport@argents.com                   | ARGENTS$2026       |
      | domestic@argents.com                          | ARGENTS$2026       |
      | dweigand@argents.com                          | ARGENTS$2026       |
      | edeaton@argents.com                           | ARGENTS$2026       |
      | fulfillment@argents.com                       | ARGENTS$2026       |
      | jfloresca@argents.com                         | ARGENTS$2026       |
      | oceanexport@argents.com                       | ARGENTS$2026       |
      | nyc@arkmanusa.com                             | ARKMAN$2026        |
      | brupp@asamerica.com                           | ASA$2026           |
      | gil@agfus.com                                 | ATLANTIC$2026      |
      | rochelle@agfus.com                            | ATLANTIC$2026      |
      | caylin@agfus.com                              | ATLANTIC$2026      |
      | abigail@agfus.com                             | ATLANTIC$2026      |
      | agf.lcl@agfus.com                             | ATLANTIC$2026      |
      | joy@clfus.com                                 | ATLANTIC$2026      |
      | damon@atronglobal.com                         | ATRON$2026         |
      | daniel@atronglobal.com                        | ATRON$2026         |
      | teambr3@barnhartinc.com                       | BARNHART$2026      |
      | annie.chen@baylinkusa.com                     | BAY$2026           |
      | jimmy.chen@baylinkusa.com                     | BAY$2026           |
      | baylinkvn_19@baylinkusa.com                   | BAY$2026           |
      | baylinkvn_21@baylinkusa.com                   | BAY$2026           |
      | baylinkvn_22@baylinkusa.com                   | BAY$2026           |
      | csc3@baylinkusa.com                           | BAY$2026           |
      | oi@baylinkusa.com                             | BAY$2026           |
      | pre-alert@baylinkusa.com                      | BAY$2026           |
      | dispatch@trilogy-logistics.com                | BDK$2026           |
      | tony@beedaintl.com                            | BEEDA$2026         |
      | binexsea@binexline.com                        | BINEX$2026         |
      | erinkim@binexline.com                         | BINEX$2026         |
      | natelee@binexline.com                         | BINEX$2026         |
      | seaexp@binexline.com                          | BINEX$2026         |
      | s.jacob@blueaxisusa.com                       | BLUE$2026          |
      | m.joseph@blueaxisusa.com                      | BLUE$2026          |
      | amy.sullivan@bocintl.com                      | BOC$2026           |
      | airimp.usa@rivworldwide.com                   | BOLT$2026          |
      | jmccall@boxerfreight.com                      | BOXER$2026         |
      | alan@boxerfreight.com                         | BOXER$2026         |
      | charla@boxerfreight.com                       | BOXER$2026         |
      | matt@boxerfreight.com                         | BOXER$2026         |
      | melissa@boxerfreight.com                      | BOXER$2026         |
      | export@blifreight.com                         | BRISK$2026         |
      | export@capitalnyc.com                         | CAPITAL$2026       |
      | sherleen@cargoexpressusa.com                  | CARGO$2026         |
      | adelis.torres@cargomodules.com                | CARGO$2026         |
      | daniel.rosa@cargomodules.com                  | CARGO$2026         |
      | emelyn.marquez@cargomodules.com               | CARGO$2026         |
      | hugo.mestanza@cargomodules.com                | CARGO$2026         |
      | jennifer.pearce@cargomodules.com              | CARGO$2026         |
      | marie.catulle@cargomodules.com                | CARGO$2026         |
      | saul.blas@cargomodules.com                    | CARGO$2026         |
      | val.werner@cargomodules.com                   | CARGO$2026         |
      | matt.warren@cargomodules.com                  | CARGO$2026         |
      | michael.austin@cargomodules.com               | CARGO$2026         |
      | paige.chelucci@cargomodules.com               | CARGO$2026         |
      | tano.leanza@cargomodules.com                  | CARGO$2026         |
      | yesenia.aguilar@cargomodules.com              | CARGO$2026         |
      | raghavan@cargotransinc.com                    | CARGO$2026         |
      | chi.air@kpllogis.com                          | CARGOIS$2026       |
      | brian.kim@kpllogis.com                        | CARGOIS$2026       |
      | chi.ocean@kpllogis.com                        | CARGOIS$2026       |
      | la.ocean@kpllogis.com                         | CARGOIS$2026       |
      | nyc.air@kpllogis.com                          | CARGOIS$2026       |
      | nyc.ocean@kpllogis.com                        | CARGOIS$2026       |
      | ops@cegentransfreight.com                     | CEGENTRANS$2026    |
      | dijana.nikic@ccnausa.com                      | CENTRAL$2026       |
      | aaron.avalos@ccnausa.com                      | CENTRAL$2026       |
      | chris.blaesi@ccnausa.com                      | CENTRAL$2026       |
      | dfwops@ccnausa.com                            | CENTRAL$2026       |
      | edwin.walker@ccnausa.com                      | CENTRAL$2026       |
      | erika.molina@ccnausa.com                      | CENTRAL$2026       |
      | frank.pavone@ccnausa.com                      | CENTRAL$2026       |
      | jenny.park@centralcargo-northamerica.com      | CENTRAL$2026       |
      | jonathan.flores@ccnausa.com                   | CENTRAL$2026       |
      | lsoerensen@ccnausa.com                        | CENTRAL$2026       |
      | richard.casarez@centralcargo-northamerica.com | CENTRAL$2026       |
      | richie.casarez@ccnausa.com                    | CENTRAL$2026       |
      | roop.manne@ccnausa.com                        | CENTRAL$2026       |
      | tcalabrese@ccnausa.com                        | CENTRAL$2026       |
      | todd.cutlan@centralcargo-northamerica.com     | CENTRAL$2026       |
      | abraham.vishruth@cevalogistics.com            | CEVA$2026          |
      | anna.zagorski@cevalogistics.com               | CEVA$2026          |
      | barb.swalinkavich@cevalogistics.com           | CEVA$2026          |
      | carolina.villa@cevalogistics.com              | CEVA$2026          |
      | csocean-us-lcl@cevalogistics.com              | CEVA$2026          |
      | ext.ana.huerta@cevalogistics.com              | CEVA$2026          |
      | julia.hernandez@cevalogistics.com             | CEVA$2026          |
      | katrina.hernandez@cevalogistics.com           | CEVA$2026          |
      | li.luo@cevalogistics.com                      | CEVA$2026          |
      | michele.slaughter@cevalogistics.com           | CEVA$2026          |
      | michelle.ayala@cevalogistics.com              | CEVA$2026          |
      | natasha.betzing@cevalogistics.com             | CEVA$2026          |
      | niklaus.andino@cevalogistics.com              | CEVA$2026          |
      | nishat.anis@cevalogistics.com                 | CEVA$2026          |
      | norma.hayes@cevalogistics.com                 | CEVA$2026          |
      | sh-am-us-explcldocs@cevalogistics.com         | CEVA$2026          |
      | shichan.hu@cevalogistics.com                  | CEVA$2026          |
      | terry.pilant@schayer.com                      | CHARLES$2026       |
      | jennifer.bryant@clasquin.com                  | CLASQUIN$2026      |
      | pamela.stevens@clasquin.com                   | CLASQUIN$2026      |
      | randy.wen@clasquin.com                        | CLASQUIN$2026      |
      | sandi.marquez@clasquin.com                    | CLASQUIN$2026      |
      | normas@clearfreight.com                       | CLEAR$2026         |
      | rwzhao@click4ship.com                         | CLICK4SHIP$2026    |
      | carlo@cmcargosolutions.com                    | CM$2026            |
      | chuck@cmcglobalshipping.com                   | CMC$2026           |
      | mike@cmcglobalshipping.com                    | CMC$2026           |
      | leonore@columbialogistics.com                 | COLUMBIA$2026      |
      | jsmollen@compass-logistics.com                | COMPASS$2026       |
      | twaddell@compass-logistics.com                | COMPASS$2026       |
      | jvaldes@compass-logistics.com                 | COMPASS$2026       |
      | jhouse@coppersmith.com                        | COPPERSMITH$2026   |
      | tcatlett@coppersmith.com                      | COPPERSMITH$2026   |
      | seatro@coppersmith.com                        | COPPERSMITH$2026   |
      | ydugas@coppersmith.com                        | COPPERSMITH$2026   |
      | ordtro@coppersmith.com                        | COPPERSMITH$2026   |
      | msummers@corriganairsea.com                   | CORRIGAN$2026      |
      | carlos.garcia@craneww.com                     | CRANE$2026         |
      | charles.lilley@craneww.com                    | CRANE$2026         |
      | cmhexport@craneww.com                         | CRANE$2026         |
      | cmhops@craneww.com                            | CRANE$2026         |
      | cumminsusoceanimport@craneww.com              | CRANE$2026         |
      | daisy.minor@craneww.com                       | CRANE$2026         |
      | david.facundo@craneww.com                     | CRANE$2026         |
      | deena.dollar@craneww.com                      | CRANE$2026         |
      | edwin.mansilla@craneww.com                    | CRANE$2026         |
      | emmy.hernandez@craneww.com                    | CRANE$2026         |
      | hescraneair@craneww.com                       | CRANE$2026         |
      | hescranehazmat@craneww.com                    | CRANE$2026         |
      | iahoperations@craneww.com                     | CRANE$2026         |
      | james.tatum@craneww.com                       | CRANE$2026         |
      | jill.johnson@craneww.com                      | CRANE$2026         |
      | joey.redyke@craneww.com                       | CRANE$2026         |
      | ka.szeto@craneww.com                          | CRANE$2026         |
      | ken.lu@craneww.com                            | CRANE$2026         |
      | kourtney.nelloms@craneww.com                  | CRANE$2026         |
      | lauren.smith@craneww.com                      | CRANE$2026         |
      | lrdops@craneww.com                            | CRANE$2026         |
      | marichu.abella@craneww.com                    | CRANE$2026         |
      | megan.listi@craneww.com                       | CRANE$2026         |
      | michael.hubble@craneww.com                    | CRANE$2026         |
      | monique.rodriguez@craneww.com                 | CRANE$2026         |
      | novexportsiah@craneww.com                     | CRANE$2026         |
      | ordairexport@craneww.com                      | CRANE$2026         |
      | tabitham.smart@craneww.com                    | CRANE$2026         |
      | teara.mays@craneww.com                        | CRANE$2026         |
      | teri.chouest@craneww.com                      | CRANE$2026         |
      | terri@crestcontainers-us.com                  | CREST$2026         |
      | karen.usa@dartglobal.com                      | DART$2026          |
      | natasha.usa@dartglobal.com                    | DART$2026          |
      | dbgroupchi@dbgroup.net                        | DB$2026            |
      | operations.oceanimport.mia@dbgroup.net        | DB$2026            |
      | tina.petrovic@dbgroup.net                     | DB$2026            |
      | elaine@dcintlus.com                           | DECHUAN$2026       |
      | kris@dcintlus.com                             | DECHUAN$2026       |
      | susan@dcintlus.com                            | DECHUAN$2026       |
      | airimport@deltamaxchicago.com                 | DELTAMAX$2026      |
      | oceanimport@deltamaxchicago.com               | DELTAMAX$2026      |
      | enarvaez@dgm-usa.com                          | DGM$2026           |
      | import.us@dgs-logistics.com                   | DGS$2026           |
      | patrick.jacob@dgs-logistics.com               | DGS$2026           |
      | ae_dimnyc@dimerco.com                         | DIMERCO$2026       |
      | ae_dimnyc@dimerco.com                         | DIMERCO$2026       |
      | ai_dimnyc@dimerco.com                         | DIMERCO$2026       |
      | michael_m_horan@dimerco.com                   | DIMERCO$2026       |
      | ocean_dimnyc@dimerco.com                      | DIMERCO$2026       |
      | stanley_s_li@dimerco.com                      | DIMERCO$2026       |
      | ae_operations_dimord@dimerco.com              | DIMERCO$2026       |
      | ai_dimord@dimerco.com                         | DIMERCO$2026       |
      | cathy_c_ru@dimerco.com                        | DIMERCO$2026       |
      | cvg1652227                                    | DIMERCO$2026       |
      | ken_wan@dimerco.com                           | DIMERCO$2026       |
      | ocean_operations_dimord@dimerco.com           | DIMERCO$2026       |
      | docs@dit-chi.com                              | DIT$2026           |
      | leahl@dit-chi.com                             | DIT$2026           |
      | stevens@dit-chi.com                           | DIT$2026           |
      | aaronw@dit-lax.com                            | DOLPHIN$2026       |
      | eric.r@dit-lax.com                            | DOLPHIN$2026       |
      | harmonys@dit-lax.com                          | DOLPHIN$2026       |
      | samz@dit-lax.com                              | DOLPHIN$2026       |
      | love2ship@doveshipping.com                    | DOVE$2026          |
      | esther.chong@cjlogisticsamerica.com           | DSC$2026           |
      | jh.lim25@cjlogisticsamerica.com               | DSC$2026           |
      | sara.kim@cjlogisticsamerica.com               | DSC$2026           |
      | dipesh@dtdc.com                               | DTDC$2026          |
      | freight.quotes@dtdc.com                       | DTDC$2026          |
      | rajesh.thakur@dtdc.com                        | DTDC$2026          |
      | sampath@dtdc.com                              | DTDC$2026          |
      | shailesh.hegde@dtdc.com                       | DTDC$2026          |
      | airexp@dynasty-lax.com                        | DYNASTY$2026       |
      | airimp@dynasty-lax.com                        | DYNASTY$2026       |
      | oceanimp@dynasty-lax.com                      | DYNASTY$2026       |
      | erlin.m@dynshippingllc.com                    | DYNASTY$2026       |
      | judy.huang@dynastyord.com                     | DYNASTY$2026       |
      | leo.yu@dynastyord.com                         | DYNASTY$2026       |
      | mike.situ@dynastyord.com                      | DYNASTY$2026       |
      | tom.wang@dynastyord.com                       | DYNASTY$2026       |
      | wendy.chen@dynastyord.com                     | DYNASTY$2026       |
      | international@ealogistics.com                 | EA$2026            |
      | team1@ealogistics.com                         | EA$2026            |
      | team2@ealogistics.com                         | EA$2026            |
      | team3@ealogistics.com                         | EA$2026            |
      | brian.estrada@ecospheregl.com                 | ECOSPHERE$2026     |
      | cyndil@ecospheregl.com                        | ECOSPHERE$2026     |
      | imports@embassyfreightusa.com                 | EMBASSY$2026       |
      | michaelc@embassyfreightusa.com                | EMBASSY$2026       |
      | oskerc@embassyfreightusa.com                  | EMBASSY$2026       |
      | shellym@embassyfreightusa.com                 | EMBASSY$2026       |
      | dallas.dunn@emotrans.com                      | EMO$2026           |
      | adrienne.decesare@emotrans.com                | EMO$2026           |
      | john.boskey@emotrans.com                      | EMO$2026           |
      | kerry-ann.mckenzie@emotrans.com               | EMO$2026           |
      | gudrun.gabriel@emotrans.com                   | EMO$2026           |
      | hannah.kirby@emotrans.com                     | EMO$2026           |
      | jonathan.medina@emotrans.com                  | EMO$2026           |
      | keith.laflamme@emotrans.com                   | EMO$2026           |
      | ryan.bell@emotrans.com                        | EMO$2026           |
      | justin.power@emotrans.com                     | EMO$2026           |
      | mia.danh@emotrans.com                         | EMO$2026           |
      | bwiimport@emotrans.com                        | EMO$2026           |
      | dennis.barrett@emotrans.com                   | EMO$2026           |
      | kristin.leigh@emotrans.com                    | EMO$2026           |
      | emocleimp@emotrans.com                        | EMO$2026           |
      | belinda.hamilton@emotrans.com                 | EMO$2026           |
      | daniel.bayes@emotrans.com                     | EMO$2026           |
      | hillary.earle@emotrans.com                    | EMO$2026           |
      | melissa.reames@emotrans.com                   | EMO$2026           |
      | samantha.lee@emotrans.com                     | EMO$2026           |
      | collette.rogers@emotrans.com                  | EMO$2026           |
      | samantha.nowitzke@emotrans.com                | EMO$2026           |
      | tracey.havican@emotrans.com                   | EMO$2026           |
      | wendy.nowitzke@emotrans.com                   | EMO$2026           |
      | dtw-airexport@emotrans.com                    | EMO$2026           |
      | dtw-domestic@emotrans.com                     | EMO$2026           |
      | briana.castro@emotrans.com                    | EMO$2026           |
      | eder.santiago@emotrans.com                    | EMO$2026           |
      | jennifer.kite@emotrans.com                    | EMO$2026           |
      | claudia.antunez@emotrans.com                  | EMO$2026           |
      | raquel.nascimento@emotrans.com                | EMO$2026           |
      | stephanie.stephens@emotrans.com               | EMO$2026           |
      | thorsten.jankowiak@emotrans.com               | EMO$2026           |
      | mike.yang@emotrans.com                        | EMO$2026           |
      | miaimports@emotrans.com                       | EMO$2026           |
      | gabriel.turner@emotrans.com                   | EMO$2026           |
      | gregory.zieman@emotrans.com                   | EMO$2026           |
      | hunter.afzalirad@emotrans.com                 | EMO$2026           |
      | michael.miller@emotrans.com                   | EMO$2026           |
      | lionel.liao@emotrans.com                      | EMO$2026           |
      | rachaele.riley@emotrans.com                   | EMO$2026           |
      | shon.mcqueen@emotrans.com                     | EMO$2026           |
      | yadzia.lugo@emotrans.com                      | EMO$2026           |
      | emojfk-oceanimport@emotrans.com               | EMO$2026           |
      | nadia.jairam@emotrans.com                     | EMO$2026           |
      | juana.morales@emotrans.com                    | EMO$2026           |
      | robert.kokoszka@emotrans.com                  | EMO$2026           |
      | olivia.malliaras@emotrans.com                 | EMO$2026           |
      | mark.burris@emotrans.com                      | EMO$2026           |
      | shizue.stuber@emotrans.com                    | EMO$2026           |
      | cynthia.solano@emotrans.com                   | EMO$2026           |
      | grant.kochey@emotrans.com                     | EMO$2026           |
      | jerome.campbell@emotrans.com                  | EMO$2026           |
      | kimberly.newton@emotrans.com                  | EMO$2026           |
      | leslie.jacobs@emotrans.com                    | EMO$2026           |
      | marion.antonio@emotrans.com                   | EMO$2026           |
      | sandra.rosenbaum@emotrans.com                 | EMO$2026           |
      | ops.lax@eurocargo.com                         | EURO$2026          |
      | ops4.lax@eurocargo.com                        | EURO$2026          |
      | joeyi.zhou@expresslinecorp.com                | EXPRESS$2026       |
      | cindyt@expresslinecorp.com                    | EXPRESS$2026       |
      | denish@expresslinecorp.com                    | EXPRESS$2026       |
      | gina.tsai.jfk@expresslinecorp.com             | EXPRESS$2026       |
      | janel@expresslinecorp.com                     | EXPRESS$2026       |
      | jenny.tran.jfk@expresslinecorp.com            | EXPRESS$2026       |
      | jerryy@expresslinecorp.com                    | EXPRESS$2026       |
      | jim.chen.jfk@expresslinecorp.com              | EXPRESS$2026       |
      | lori.du.jfk@expresslinecorp.com               | EXPRESS$2026       |
      | cailian@expresslinecorp.com                   | EXPRESS$2026       |
      | helen.ye.chi@expresslinecorp.com              | EXPRESS$2026       |
      | paul.chung.chi@expresslinecorp.com            | EXPRESS$2026       |
      | sharon.chen.chi@expresslinecorp.com           | EXPRESS$2026       |
      | tracy.ye.chi@expresslinecorp.com              | EXPRESS$2026       |
      | shannon.liu.chi@expresslinecorp.com           | EXPRESS$2026       |
      | susan.enkhbold.chi@expresslinecorp.com        | EXPRESS$2026       |
      | frederic.vaccaretti@fatton.com                | FATTON$2026        |
      | importlax@fatton.com                          | FATTON$2026        |
      | internjfk@fatton.com                          | FATTON$2026        |
      | lea.chamoulaud@fatton.com                     | FATTON$2026        |
      | renaud.mellier@fatton.com                     | FATTON$2026        |
      | sofiane.benhamouda@fatton.com                 | FATTON$2026        |
      | roberto.largaespada@fedex.com                 | FEDEX$2026         |
      | yibo.hao@fedex.com                            | FEDEX$2026         |
      | cs@fpslogistic.com                            | FPS$2026           |
      | louis@fpslogistic.com                         | FPS$2026           |
      | atle.usnyc@freightsystems.com                 | FREIGHT$2026       |
      | jella.usnyc@freightsystems.com                | FREIGHT$2026       |
      | rachelle.usnyc@freightsystems.com             | FREIGHT$2026       |
      | austin@airseaintl.net                         | FREIGHTLINK$2026   |
      | jody@freightlink.net                          | FREIGHTLINK$2026   |
      | mackenzie@freightlink.net                     | FREIGHTLINK$2026   |
      | bonarhee@gnbusa.com                           | G$2026             |
      | esther.kim@gnbusa.com                         | G$2026             |
      | juliejy9556@gmail.com                         | G$2026             |
      | sun.park@gnbusa.com                           | G$2026             |
      | catherine.gregerson@gw-world.com              | GEBRUDER$2026      |
      | ground@gcargo.com                             | GLOBAL$2026        |
      | marvinj@globalf.com                           | GLOBAL$2026        |
      | mayx@globalf.com                              | GLOBAL$2026        |
      | michaeln@globalf.com                          | GLOBAL$2026        |
      | stefanie.roberts@goairlandsea.com             | GO$2026            |
      | exports.hou@greenworldwide.com                | GREEN$2026         |
      | luis.villavicencio@greenworldwide.com         | GREEN$2026         |
      | hsiao-ling.fan@greenworldwide.com             | GREEN$2026         |
      | shabaz@gmlusa.net                             | GREENWICH$2026     |
      | shaun@gmlusa.net                              | GREENWICH$2026     |
      | export-atl@us.hh-express.com                  | HANKYU$2026        |
      | s.williams@us.hh-express.com                  | HANKYU$2026        |
      | air-usa.list@bondex.com.cn                    | HAPTRANS$2026      |
      | matthew.xu@bondex.com.cn                      | HAPTRANS$2026      |
      | alexander.glukhoman@hellmann.com              | HELLMAN $2026      |
      | carla.mills@hellmann.com                      | HELLMAN $2026      |
      | cmills@hellmann.com                           | HELLMAN $2026      |
      | crystal.carr@hellmann.com                     | HELLMAN $2026      |
      | caleb.buchel@heneways.com                     | HENEWAYS$2026      |
      | cody.halik@heneways.com                       | HENEWAYS$2026      |
      | john.strand@heneways.com                      | HENEWAYS$2026      |
      | ryan.ho@heneways.com                          | HENEWAYS$2026      |
      | jocelyn@himatexpress.com                      | HI$2026            |
      | penelope@himatexpress.com                     | HI$2026            |
      | hscvg@highwaysandskyways.com                  | HIGHWAYS$2026      |
      | lundys@highwaysandskyways.com                 | HIGHWAYS$2026      |
      | csinclair@ibexfreight.com                     | IBEX$2026          |
      | jcarroll@ibexfreight.com                      | IBEX$2026          |
      | lmyllek@ibexfreight.com                       | IBEX$2026          |
      | mcarroll@ibexfreight.com                      | IBEX$2026          |
      | mfernandes@ibexfreight.com                    | IBEX$2026          |
      | ncuevas@ibexfreight.com                       | IBEX$2026          |
      | syaport@ibexfreight.com                       | IBEX$2026          |
      | tajeti@ibexfreight.com                        | IBEX$2026          |
      | jasonr@ict-usa.com                            | ICT$2026           |
      | lflores@imperativelogistics.com               | IMPERATIVE$2026    |
      | wschuster@imperativelogistics.com             | IMPERATIVE$2026    |
      | airimport.chi@impexgls.com                    | IMPEX$2026         |
      | export.chi@impexgls.com                       | IMPEX$2026         |
      | oceanimport.chi@impexgls.com                  | IMPEX$2026         |
      | import.lax@impexgls.com                       | IMPEX$2026         |
      | francisli@infinitytransusa.com                | INFINITY$2026      |
      | stevenli@infinitytransusa.com                 | INFINITY$2026      |
      | tintinthaw@infinitytransusa.com               | INFINITY$2026      |
      | joseph@interport-cargo.com                    | INTERPORT$2026     |
      | tony@interport-cargo.com                      | INTERPORT$2026     |
      | op1@jamesworldwide.com                        | JAMES$2026         |
      | pcurry@jcilogistics.com                       | JCI$2026           |
      | adrian.martinez@jetspeed-usa.com              | JET$2026           |
      | arantxa.simbala@jetspeed-usa.com              | JET$2026           |
      | carol.garcia@jetspeed-usa.com                 | JET$2026           |
      | casey.huebsch@jetspeed-usa.com                | JET$2026           |
      | michael.gordon@jetspeed-usa.com               | JET$2026           |
      | sue.dolenak@jetspeed-usa.com                  | JET$2026           |
      | peter@jhj.us                                  | JHJ$2026           |
      | sal@jhj.us                                    | JHJ$2026           |
      | tiffany@jhj.us                                | JHJ$2026           |
      | jit5@jitusalogistics.com                      | JIT$2026           |
      | wenli.qin@jitusalogistics.com                 | JIT$2026           |
      | bhuisman@junologistics.com                    | JUNO$2026          |
      | esantillan@junologistics.com                  | JUNO$2026          |
      | jbottoms@junologistics.com                    | JUNO$2026          |
      | olive@karrellis.com                           | KARR$2026          |
      | rwalsh@karrellis.com                          | KARR$2026          |
      | tom@karrellis.com                             | KARR$2026          |
      | atloceanexp@am.kwe.com                        | KINTETSU$2026      |
      | hadiyah.khan@am.kwe.com                       | KINTETSU$2026      |
      | justin.sisouvankham@am.kwe.com                | KINTETSU$2026      |
      | amy.carmichael@am.kwe.com                     | KINTETSU$2026      |
      | jessica.hedger@am.kwe.com                     | KINTETSU$2026      |
      | dararith.khun@am.kwe.com                      | KINTETSU$2026      |
      | dfwbb.mailbox@kwe.com                         | KINTETSU$2026      |
      | kwidfw.mailbox@kwe.com                        | KINTETSU$2026      |
      | es@konektacom.com                             | KONEKTACOM$2026    |
      | bessie.yi@kuehne-nagel.com                    | KUEHNE$2026        |
      | danny.hong@kuehne-nagel.com                   | KUEHNE$2026        |
      | adam.silvenis@kuehne-nagel.com                | KUEHNE$2026        |
      | ana.k.gomez@kuehne-nagel.com                  | KUEHNE$2026        |
      | andrew.tate@kuehne-nagel.com                  | KUEHNE$2026        |
      | audrey.wilinski@kuehne-nagel.com              | KUEHNE$2026        |
      | bridget.droelle@kuehne-nagel.com              | KUEHNE$2026        |
      | brittney.williams@kuehne-nagel.com            | KUEHNE$2026        |
      | caitlyn.scanlon@kuehne-nagel.com              | KUEHNE$2026        |
      | chanel.wood-norman@kuehne-nagel.com           | KUEHNE$2026        |
      | colin.balnave@kuehne-nagel.com                | KUEHNE$2026        |
      | contactcts@odysseylogistics.com               | KUEHNE$2026        |
      | david.obrien@kuehne-nagel.com                 | KUEHNE$2026        |
      | demetrius.coad@kuehne-nagel.com               | KUEHNE$2026        |
      | emmett.mitchell@kuehne-nagel.com              | KUEHNE$2026        |
      | erin.murphy@kuehne-nagel.com                  | KUEHNE$2026        |
      | frances.s.brown@kuehne-nagel.com              | KUEHNE$2026        |
      | frank.sheppard@kuehne-nagel.com               | KUEHNE$2026        |
      | gabriella.alcamo@kuehne-nagel.com             | KUEHNE$2026        |
      | gino.genrich@kuehne-nagel.com                 | KUEHNE$2026        |
      | girlie.roque@kuehne-nagel.com                 | KUEHNE$2026        |
      | ivana.adams@kuehne-nagel.com                  | KUEHNE$2026        |
      | jackson.freeman@kuehne-nagel.com              | KUEHNE$2026        |
      | jacob.dettmer@kuehne-nagel.com                | KUEHNE$2026        |
      | jacqueline.gross@kuehne-nagel.com             | KUEHNE$2026        |
      | jessica.mossner@kuehne-nagel.com              | KUEHNE$2026        |
      | joel.quiroz@kuehne-nagel.com                  | KUEHNE$2026        |
      | john.williams@kuehne-nagel.com                | KUEHNE$2026        |
      | joseph.horth@kuehne-nagel.com                 | KUEHNE$2026        |
      | joshua.milewski@kuehne-nagel.com              | KUEHNE$2026        |
      | keionna.adair@kuehne-nagel.com                | KUEHNE$2026        |
      | kevin.vuong@kuehne-nagel.com                  | KUEHNE$2026        |
      | kim.kostevich@kuehne-nagel.com                | KUEHNE$2026        |
      | kndet.ae@kuehne-nagel.com                     | KUEHNE$2026        |
      | laquida.stanford@kuehne-nagel.com             | KUEHNE$2026        |
      | laura.dudek@kuehne-nagel.com                  | KUEHNE$2026        |
      | lclexpecommerce@kuehne-nagel.com              | KUEHNE$2026        |
      | lia.gaglio@kuehne-nagel.com                   | KUEHNE$2026        |
      | lillia.lattanzi@kuehne-nagel.com              | KUEHNE$2026        |
      | logan.ceccarelli@kuehne-nagel.com             | KUEHNE$2026        |
      | lura.smith@kuehne-nagel.com                   | KUEHNE$2026        |
      | mary.decelle@kuehne-nagel.com                 | KUEHNE$2026        |
      | mateo.trevino@kuehne-nagel.com                | KUEHNE$2026        |
      | matthew.holmes@kuehne-nagel.com               | KUEHNE$2026        |
      | megan.gibson@kuehne-nagel.com                 | KUEHNE$2026        |
      | natasha.mitchell@kuehne-nagel.com             | KUEHNE$2026        |
      | nicholas.hickey@kuehne-nagel.com              | KUEHNE$2026        |
      | occ.cat@kuehne-nagel.com                      | KUEHNE$2026        |
      | racquel.hines@kuehne-nagel.com                | KUEHNE$2026        |
      | randi.hutchison@kuehne-nagel.com              | KUEHNE$2026        |
      | richard.collins@kuehne-nagel.com              | KUEHNE$2026        |
      | roman.alcantar@kuehne-nagel.com               | KUEHNE$2026        |
      | scott.tutas@kuehne-nagel.com                  | KUEHNE$2026        |
      | seamus.imes@kuehne-nagel.com                  | KUEHNE$2026        |
      | sheila.katus@kuehne-nagel.com                 | KUEHNE$2026        |
      | toiya.waller@kuehne-nagel.com                 | KUEHNE$2026        |
      | william.brock@kuehne-nagel.com                | KUEHNE$2026        |
      | acastillo@laufer.com                          | LAUFER$2026        |
      | bherr@laufer.com                              | LAUFER$2026        |
      | dawns@laufer.com                              | LAUFER$2026        |
      | jmarano@laufer.com                            | LAUFER$2026        |
      | mrumple@laufer.com                            | LAUFER$2026        |
      | shamre@laufer.com                             | LAUFER$2026        |
      | thuynh@laufer.com                             | LAUFER$2026        |
      | jshen@laufer.com                              | LAUFER$2026        |
      | jeanp@leaderairsea.com                        | LEADER$2026        |
      | sandral@leaderairsea.com                      | LEADER$2026        |
      | dwang@leader-mutual.com                       | LEADER$2026        |
      | syang@leader-mutual.com                       | LEADER$2026        |
      | tqian@leader-mutual.com                       | LEADER$2026        |
      | sharon@leader-mutual.com                      | LEADER$2026        |
      | dfw-import@leader-mutual.com                  | LEADER$2026        |
      | exportsea@leader-mutual.com                   | LEADER$2026        |
      | ord-export@leader-mutual.com                  | LEADER$2026        |
      | twang@leader-mutual.com                       | LEADER$2026        |
      | chicago@leman.com                             | LEMAN$2026         |
      | john.reid@leman.com                           | LEMAN$2026         |
      | mke.oceanimport@leman.com                     | LEMAN$2026         |
      | ckahraman@us-logfret.com                      | LOGFRET,$2026      |
      | ggungor@us-logfret.com                        | LOGFRET,$2026      |
      | pgarcia@us-logfret.com                        | LOGFRET,$2026      |
      | pmansur@us-logfret.com                        | LOGFRET,$2026      |
      | sferris@us-logfret.com                        | LOGFRET,$2026      |
      | rebecca.winters@hitachi-vht.com               | LOGISTEED$2026     |
      | wa.situ@logisteed-america.com                 | LOGISTEED$2026     |
      | john.debelak@logwin-logistics.com             | LOGWIN$2026        |
      | customerserv@mmdirectexp.com                  | M$2026             |
      | hlynch@mmexplogistics.com                     | M$2026             |
      | anna.burgos@maersk.com                        | MAERSK$2026        |
      | atlairexport@maersk.com                       | MAERSK$2026        |
      | atlstationimport@maersk.com                   | MAERSK$2026        |
      | chiairimpops@maersk.com                       | MAERSK$2026        |
      | erin.gustafson@maersk.com                     | MAERSK$2026        |
      | eureka.woods@maersk.com                       | MAERSK$2026        |
      | harry.sutcliffe@maersk.com                    | MAERSK$2026        |
      | hazel.quitlong@lns.maersk.com                 | MAERSK$2026        |
      | heissel.basanta@maersk.com                    | MAERSK$2026        |
      | hollie.tucker@maersk.com                      | MAERSK$2026        |
      | jazmin.hernandez@lns.maersk.com               | MAERSK$2026        |
      | jessica.hernandez@lns.maersk.com              | MAERSK$2026        |
      | kenneth.evans@maersk.com                      | MAERSK$2026        |
      | laxairexport@maersk.com                       | MAERSK$2026        |
      | maricarmen.munson@lns.maersk.com              | MAERSK$2026        |
      | natalia.caballero@maersk.com                  | MAERSK$2026        |
      | nicole.lyles@maersk.com                       | MAERSK$2026        |
      | ord_airexport@maersk.com                      | MAERSK$2026        |
      | robert.guzman@maersk.com                      | MAERSK$2026        |
      | ronice.mullins@lns.maersk.com                 | MAERSK$2026        |
      | sandra.cartledge@lns.maersk.com               | MAERSK$2026        |
      | wanda.sherrer@lns.maersk.com                  | MAERSK$2026        |
      | atlexportair@mallorygroup.com                 | MALLORY$2026       |
      | brian.johnson@mallorygroup.com                | MALLORY$2026       |
      | lindah@mallorygroup.com                       | MALLORY$2026       |
      | teresag@mallorygroup.com                      | MALLORY$2026       |
      | qsamuel@mgfgroup.com                          | MANITOULIN$2026    |
      | kostia@mantlog.com                            | MANT$2026          |
      | tiffanyy@mantlog.com                          | MANT$2026          |
      | briankim@maxigl.com                           | MAX$2026           |
      | kenny@maxigl.com                              | MAX$2026           |
      | maxchi@maxigl.com                             | MAX$2026           |
      | maxinfo@maxigl.com                            | MAX$2026           |
      | maxord@maxigl.com                             | MAX$2026           |
      | peteryi@maxigl.com                            | MAX$2026           |
      | choee@mlac.com                                | MITSUBISHI$2026    |
      | colburnh@mlac.com                             | MITSUBISHI$2026    |
      | husicn@mlac.com                               | MITSUBISHI$2026    |
      | ikesuem@mlac.com                              | MITSUBISHI$2026    |
      | rudnickj@mlac.com                             | MITSUBISHI$2026    |
      | rutak@mlac.com                                | MITSUBISHI$2026    |
      | schramekk@mlac.com                            | MITSUBISHI$2026    |
      | jensenb@mlac.com                              | MITSUBISHI$2026    |
      | sianoc@mlac.com                               | MITSUBISHI$2026    |
      | marionj@mlac.com                              | MITSUBISHI$2026    |
      | doobayj@mlac.com                              | MITSUBISHI$2026    |
      | ijoan@mlac.com                                | MITSUBISHI$2026    |
      | rupaniv@mlac.com                              | MITSUBISHI$2026    |
      | coo@mtselp.com                                | MOUNTAIN$2026      |
      | operations@mtselp.com                         | MOUNTAIN$2026      |
      | chris.chen@mslglobalexp.com                   | MSL$2026           |
      | emma.zhang@mslglobalexp.com                   | MSL$2026           |
      | fulton.lin@mslglobalexp.com                   | MSL$2026           |
      | gang.chen@mslglobalexp.com                    | MSL$2026           |
      | joann.song@mslglobalexp.com                   | MSL$2026           |
      | johnson.yeung@mslglobalexp.com                | MSL$2026           |
      | lcl@mslglboalexp.com                          | MSL$2026           |
      | lcl@mslglobalexp.com                          | MSL$2026           |
      | ryan.chen@mslglobalexp.com                    | MSL$2026           |
      | sam.jia@mslglobalexp.com                      | MSL$2026           |
      | sharon.thanh@mslglobalexp.com                 | MSL$2026           |
      | yuri.shen@mslglobalexp.com                    | MSL$2026           |
      | jason.bodine@mti-worldwide.com                | MTI$2026           |
      | kevin.almond@mti-worldwide.com                | MTI$2026           |
      | daniel.miao@newmarinenyc.com                  | NEW$2026           |
      | don.tang@newmarinenyc.com                     | NEW$2026           |
      | julie.chung@newmarinenyc.com                  | NEW$2026           |
      | lena.liu@newmarinenyc.com                     | NEW$2026           |
      | akiko.pugh@nipponexpress.com                  | NIPPON$2026        |
      | eben.kilson@nipponexpress.com                 | NIPPON$2026        |
      | jill.eayres@nipponexpress.com                 | NIPPON$2026        |
      | kumiko.kk.kimura@nipponexpress.com            | NIPPON$2026        |
      | vanessa.ramos@nipponexpress.com               | NIPPON$2026        |
      | lax031@nitusa.com                             | NISSIN$2026        |
      | atlairexport@nnrusa.com                       | NNR$2026           |
      | fajensen@nnrusa.com                           | NNR$2026           |
      | johba@nnrusa.com                              | NNR$2026           |
      | amde@ntgairocean.com                          | NTG$2026           |
      | anm@ntgairocean.com                           | NTG$2026           |
      | arus@ntgairocean.com                          | NTG$2026           |
      | ctu@ntgairocean.com                           | NTG$2026           |
      | dtu@ntgairocean.com                           | NTG$2026           |
      | kasp@ntgairocean.com                          | NTG$2026           |
      | kna@ntgairocean.com                           | NTG$2026           |
      | ksh@ntgairocean.com                           | NTG$2026           |
      | lmz@ntgairocean.com                           | NTG$2026           |
      | lri@ntgairocean.com                           | NTG$2026           |
      | mal@ntgairocean.com                           | NTG$2026           |
      | mama@ntgairocean.com                          | NTG$2026           |
      | mem@ntgairocean.com                           | NTG$2026           |
      | mgr@ntgairocean.com                           | NTG$2026           |
      | mos@ntgairocean.com                           | NTG$2026           |
      | pawa@ntgairocean.com                          | NTG$2026           |
      | pwa@ntgairocean.com                           | NTG$2026           |
      | rba@ntgairocean.com                           | NTG$2026           |
      | rewa@ntgairocean.com                          | NTG$2026           |
      | rtu@ntgairocean.com                           | NTG$2026           |
      | spa@ntgairocean.com                           | NTG$2026           |
      | spo@ntgairocean.com                           | NTG$2026           |
      | swi@ntgairocean.com                           | NTG$2026           |
      | tsc@ntgairocean.com                           | NTG$2026           |
      | wba@ntgairocean.com                           | NTG$2026           |
      | yru@ntgairocean.com                           | NTG$2026           |
      | airimport.nyc@francovago.com                  | NX$2026            |
      | airimport.nyc@nxlifestyleforwarding.us        | NX$2026            |
      | oceanimport.nyc@francovago.com                | NX$2026            |
      | oceanimport.nyc@nxlifestyleforwarding.us      | NX$2026            |
      | russamee.crain@oiaglobal.com                  | OIA$2026           |
      | johnny.dimasso@oiaglobal.com                  | OIA$2026           |
      | max.shepherd@oiaglobal.com                    | OIA$2026           |
      | frank.o@osffreight.com                        | OSF$2026           |
      | blanca@panpacificusa.com                      | PAN$2026           |
      | cocampo@panpacificusa.com                     | PAN$2026           |
      | ericav@panpacificusa.com                      | PAN$2026           |
      | fyonzon@panpacificusa.com                     | PAN$2026           |
      | jessica@panpacificusa.com                     | PAN$2026           |
      | nally@panpacificusa.com                       | PAN$2026           |
      | quotes@panpacificusa.com                      | PAN$2026           |
      | alan.ritchie@petrasco-energy.com              | PETRASCO$2026      |
      | mohammed.shareef@petrasco-energy.com          | PETRASCO$2026      |
      | rhett.bates@petrasco-energy.com               | PETRASCO$2026      |
      | edgar.aldana@phoenixintlinc.com               | PHOENIX$2026       |
      | john.denardo@phoenixintlinc.com               | PHOENIX$2026       |
      | dexter.kekauoha@platinumcargo.com             | PLATINUM$2026      |
      | hugo.zaragoza@platinumcargo.com               | PLATINUM$2026      |
      | janiece.tarver@platinumcargo.com              | PLATINUM$2026      |
      | jeremy.hodal@platinumcargo.com                | PLATINUM$2026      |
      | jody.hujing@platinumcargo.com                 | PLATINUM$2026      |
      | leon.diaz@platinumcargo.com                   | PLATINUM$2026      |
      | msp@platinumcargo.com                         | PLATINUM$2026      |
      | ord@platinumcargo.com                         | PLATINUM$2026      |
      | sharon.gribble@platinumcargo.com              | PLATINUM$2026      |
      | shawn.taylor@platinumcargo.com                | PLATINUM$2026      |
      | toni.palacioss@platinumcargo.com              | PLATINUM$2026      |
      | zach.maclachlan@platinumcargo.com             | PLATINUM$2026      |
      | jparker@pointgl.com                           | POINT$2026         |
      | rschaeffer@pointgl.com                        | POINT$2026         |
      | twingstedt@pointgl.com                        | POINT$2026         |
      | uwolak@pointgl.com                            | POINT$2026         |
      | ajaydonde@primointl.com                       | PRIMO$2026         |
      | jenna.scott@priorityimex.com                  | PRIORITY$2026      |
      | ax@psplogisticsinc.com                        | PSP$2026           |
      | import@psplogisticsinc.com                    | PSP$2026           |
      | oxf@psplogisticsinc.com                       | PSP$2026           |
      | ivy@qecww-usa.com                             | QEC$2026           |
      | diane@qxintl.com                              | QUALITY$2026       |
      | phoenixs@quartzlax.com                        | QUARTZ$2026        |
      | wanic@quartzlax.com                           | QUARTZ$2026        |
      | airimport.dfw@airgroup.com                    | RADIANT$2026       |
      | ajenkins.stl@airgroup.com                     | RADIANT$2026       |
      | blucas-garcia.bfi@radiantdelivers.com         | RADIANT$2026       |
      | blucas-garcia.sea@radiantdelivers.com         | RADIANT$2026       |
      | bmcclay@adcomworldwide.com                    | RADIANT$2026       |
      | bos2@adcomworldwide.com                       | RADIANT$2026       |
      | cltops@adcomworldwide.com                     | RADIANT$2026       |
      | cltops@adocmworldwide.com                     | RADIANT$2026       |
      | cmhops@airgroup.com                           | RADIANT$2026       |
      | denint@adcomworldwide.com                     | RADIANT$2026       |
      | dfwops@airgroup.com                           | RADIANT$2026       |
      | dshutey@adcomworldwide.com                    | RADIANT$2026       |
      | dtw@radiantdelivers.com                       | RADIANT$2026       |
      | fdesio.phl@radiantdelivers.com                | RADIANT$2026       |
      | finial@airgroup.com                           | RADIANT$2026       |
      | flopez.sju@airgroup.com                       | RADIANT$2026       |
      | indops@airgroup.com                           | RADIANT$2026       |
      | jfkdomestic@radiantdelivers.com               | RADIANT$2026       |
      | jgriffin.bos@dbaco.com                        | RADIANT$2026       |
      | jpurcell.phl@radiantdelivers.com              | RADIANT$2026       |
      | kschaudel.las@airgroup.com                    | RADIANT$2026       |
      | oceanexport.dfw@airgroup.com                  | RADIANT$2026       |
      | oceanimport.dfw@airgroup.com                  | RADIANT$2026       |
      | phumes.phl@radiantdelivers.com                | RADIANT$2026       |
      | pitquotes@adcomworldwide.com                  | RADIANT$2026       |
      | rguerra.mht@airgroup.com                      | RADIANT$2026       |
      | stlops@airgroup.com                           | RADIANT$2026       |
      | tfemling.bfi@radiantdelivers.com              | RADIANT$2026       |
      | tracking.msp@radiantdelivers.com              | RADIANT$2026       |
      | usanetwork@dbaco.com                          | RADIANT$2026       |
      | benghusen.msp@radiantdelivers.com             | RADIANT$2026       |
      | exportoceanmsp@radiantdelivers.com            | RADIANT$2026       |
      | jcollins.msp@radiantdelivers.com              | RADIANT$2026       |
      | airimport@radiuscargo.com                     | RADIUS$2026        |
      | anthonyc@radiuscargo.com                      | RADIUS$2026        |
      | chicago@radiuscargo.com                       | RADIUS$2026        |
      | chicagoairexport@radiuscargo.com              | RADIUS$2026        |
      | chicagoairimport@radiuscargo.com              | RADIUS$2026        |
      | chicagooceanexport@radiuscargo.com            | RADIUS$2026        |
      | chicagooceanimport@radiuscargo.com            | RADIUS$2026        |
      | damond@radiuscargo.com                        | RADIUS$2026        |
      | deborad@radiuscargo.com                       | RADIUS$2026        |
      | domestic@radiuscargo.com                      | RADIUS$2026        |
      | jasonw@radiuscargo.com                        | RADIUS$2026        |
      | jeromec@radiuscargo.com                       | RADIUS$2026        |
      | johnh@radiuscargo.com                         | RADIUS$2026        |
      | miami@radiuscargo.com                         | RADIUS$2026        |
      | oceanimport@radiuscargo.com                   | RADIUS$2026        |
      | samanthap@radiuscargo.com                     | RADIUS$2026        |
      | warehouse@radiuscargo.com                     | RADIUS$2026        |
      | evlin@regentlogistics.com                     | REGENT$2026        |
      | regent@regentlogistics.com                    | REGENT$2026        |
      | t2@regentlogistics.com                        | REGENT$2026        |
      | agataw@reillyinternational.com                | REILLY$2026        |
      | barbara@reillyinternational.com               | REILLY$2026        |
      | florv@reillyinternational.com                 | REILLY$2026        |
      | stephenw@reillyinternational.com              | REILLY$2026        |
      | tatumj@reillyinternational.com                | REILLY$2026        |
      | airimport.lax@rhenus.com                      | RHENUS$2026        |
      | airexport.lax@rhenus.com                      | RHENUS$2026        |
      | leslie.morales@rhenus.com                     | RHENUS$2026        |
      | neil.narayan@rhenus.com                       | RHENUS$2026        |
      | airimport.ord@rhenus.com                      | RHENUS$2026        |
      | airexport.ord@rhenus.com                      | RHENUS$2026        |
      | maggie.zimmerman@rhenus.com                   | RHENUS$2026        |
      | airexport.atl@rhenus.com                      | RHENUS$2026        |
      | cs1.usnyc@freightsystems.com                  | RIM$2026           |
      | jennyurbana@rimlogistics.com                  | RIM$2026           |
      | melaniegayeta@rimlogistics.com                | RIM$2026           |
      | timothybayot@rimlogistics.com                 | RIM$2026           |
      | shiellarendal@rimlogistics.com                | RIM$2026           |
      | cs@rltlog.com                                 | RLT$2026           |
      | meghan@shiprose.com                           | ROSE$2026          |
      | a.savanah@rulewave.com                        | RULEWAVE$2026      |
      | c.molegraaf@rulewave.com                      | RULEWAVE$2026      |
      | freightforwarding-us@rulewave.com             | RULEWAVE$2026      |
      | oceanfreight-us@rulewave.com                  | RULEWAVE$2026      |
      | natalia@mintgl.com                            | S$2026             |
      | aendl@scangl.com                              | SCAN$2026          |
      | ajime@scangl.com                              | SCAN$2026          |
      | avoll@scangl.com                              | SCAN$2026          |
      | bellab.cle@transgroup.com                     | SCAN$2026          |
      | bnava@scangl.com                              | SCAN$2026          |
      | boi.intl@scangl.com                           | SCAN$2026          |
      | bos.intl@scangl.com                           | SCAN$2026          |
      | cle.oceanexport@scangl.com                    | SCAN$2026          |
      | crami@scangl.com                              | SCAN$2026          |
      | cvg.airimport@scangl.com                      | SCAN$2026          |
      | jasan@scangl.com                              | SCAN$2026          |
      | kskaa@scangl.com                              | SCAN$2026          |
      | lax.airexport@scangl.com                      | SCAN$2026          |
      | lax.oceanexport@scangl.com                    | SCAN$2026          |
      | mia.airexport@scangl.com                      | SCAN$2026          |
      | milei@scangl.com                              | SCAN$2026          |
      | mjohn@scangl.com                              | SCAN$2026          |
      | nfish@scangl.com                              | SCAN$2026          |
      | oceanexport@scangl.com                        | SCAN$2026          |
      | oltim@scangl.com                              | SCAN$2026          |
      | ord.oceanexport@scangl.com                    | SCAN$2026          |
      | phx.dom@scangl.com                            | SCAN$2026          |
      | rmora@scangl.com                              | SCAN$2026          |
      | slope@scangl.com                              | SCAN$2026          |
      | vgome@scangl.com                              | SCAN$2026          |
      | wbarr@scangl.com                              | SCAN$2026          |
      | henrymei@scanwell.com                         | SCANWELL$2026      |
      | winsitan@scanwell.com                         | SCANWELL$2026      |
      | adryan.mccauley@maersk.com                    | SENATOR$2026       |
      | alcl_airimport.atl@maersk.com                 | SENATOR$2026       |
      | daniel.richardson@maersk.com                  | SENATOR$2026       |
      | gsp.imp.ocfo@maersk.com                       | SENATOR$2026       |
      | hannah.headley@maersk.com                     | SENATOR$2026       |
      | jennifer.olson@maersk.com                     | SENATOR$2026       |
      | lax.bmw.import_alcl@maersk.com                | SENATOR$2026       |
      | lekisha.howell@maersk.com                     | SENATOR$2026       |
      | regina.grijalva@maersk.com                    | SENATOR$2026       |
      | sandra.ousley@atl.senator-international.com   | SENATOR$2026       |
      | sandra.ousley@maersk.com                      | SENATOR$2026       |
      | sandra.schuch@lax.senator-international.com   | SENATOR$2026       |
      | shannon.mallard@lns.maersk.com                | SENATOR$2026       |
      | william.r@lns.maersk.com                      | SENATOR$2026       |
      | yolanda.marshall@maersk.com                   | SENATOR$2026       |
      | ses-nyc@usa.com                               | SES$2026           |
      | cs@sfsystems.net                              | SF$2026            |
      | export@sfsystems.net                          | SF$2026            |
      | import@sfsystems.net                          | SF$2026            |
      | import2@sfsystems.net                         | SF$2026            |
      | op@sfsystems.net                              | SF$2026            |
      | gerald@shinexpress.com                        | SHINE$2026         |
      | julio@shinexpress.com                         | SHINE$2026         |
      | jlano@shiptechintl.com                        | SHIPTECH$2026      |
      | mnuguid@shiptechintl.com                      | SHIPTECH$2026      |
      | nwagner@shiptechintl.com                      | SHIPTECH$2026      |
      | zsmith@shiptechintl.com                       | SHIPTECH$2026      |
      | ops2@simpleforwarding.com                     | SIMPLE$2026        |
      | karthi@skyferlogistic.com                     | SKYFER$2026        |
      | krystinaz@skyferlogistic.com                  | SKYFER$2026        |
      | richardf@skyferlogistic.com                   | SKYFER$2026        |
      | syed@skyferlogistic.com                       | SKYFER$2026        |
      | vishnum@skyferlogistic.com                    | SKYFER$2026        |
      | airfreight@sladeshipping.com                  | SLADE$2026         |
      | nicol@sladeshipping.com                       | SLADE$2026         |
      | ops@sliglobal.com                             | SLI$2026           |
      | rickyt@sobelnet.com                           | SOBEL$2026         |
      | pratikd@sobelnet.com                          | SOBEL$2026         |
      | markt@sobelnet.com                            | SOBEL$2026         |
      | alewis@sobelnet.com                           | SOBEL$2026         |
      | alisar@sobelnet.com                           | SOBEL$2026         |
      | ashleyo@sobelnet.com                          | SOBEL$2026         |
      | carolineg@sobelnet.com                        | SOBEL$2026         |
      | christend@sobelnet.com                        | SOBEL$2026         |
      | oceanexp@sobelnet.com                         | SOBEL$2026         |
      | reneer@sobelnet.com                           | SOBEL$2026         |
      | us1@sonicainternational.com                   | SONICA$2026        |
      | ben.lin@sonicainternational.com               | SONICA$2026        |
      | jessica.zeng@sonicainternational.com          | SONICA$2026        |
      | jessicz.zeng@sonicainternational.com          | SONICA$2026        |
      | kiyomi.okada@sonicainternational.com          | SONICA$2026        |
      | min.lin@sonicainternational.com               | SONICA$2026        |
      | agataw@reillyinternational.com                | REILLY$2026        |
      | barbara@reillyinternational.com               | REILLY$2026        |
      | florv@reillyinternational.com                 | REILLY$2026        |
      | stephenw@reillyinternational.com              | REILLY$2026        |
      | tatumj@reillyinternational.com                | REILLY$2026        |
      | airimport.lax@rhenus.com                      | RHENUS$2026        |
      | airexport.lax@rhenus.com                      | RHENUS$2026        |
      | leslie.morales@rhenus.com                     | RHENUS$2026        |
      | neil.narayan@rhenus.com                       | RHENUS$2026        |
      | airimport.ord@rhenus.com                      | RHENUS$2026        |
      | airexport.ord@rhenus.com                      | RHENUS$2026        |
      | maggie.zimmerman@rhenus.com                   | RHENUS$2026        |
      | airexport.atl@rhenus.com                      | RHENUS$2026        |
      | cs1.usnyc@freightsystems.com                  | RIM$2026           |
      | jennyurbana@rimlogistics.com                  | RIM$2026           |
      | melaniegayeta@rimlogistics.com                | RIM$2026           |
      | timothybayot@rimlogistics.com                 | RIM$2026           |
      | shiellarendal@rimlogistics.com                | RIM$2026           |
      | cs@rltlog.com                                 | RLT$2026           |
      | meghan@shiprose.com                           | ROSE$2026          |
      | a.savanah@rulewave.com                        | RULEWAVE$2026      |
      | c.molegraaf@rulewave.com                      | RULEWAVE$2026      |
      | freightforwarding-us@rulewave.com             | RULEWAVE$2026      |
      | oceanfreight-us@rulewave.com                  | RULEWAVE$2026      |
      | natalia@mintgl.com                            | S$2026             |
      | aendl@scangl.com                              | SCAN$2026          |
      | ajime@scangl.com                              | SCAN$2026          |
      | avoll@scangl.com                              | SCAN$2026          |
      | bellab.cle@transgroup.com                     | SCAN$2026          |
      | bnava@scangl.com                              | SCAN$2026          |
      | boi.intl@scangl.com                           | SCAN$2026          |
      | bos.intl@scangl.com                           | SCAN$2026          |
      | cle.oceanexport@scangl.com                    | SCAN$2026          |
      | crami@scangl.com                              | SCAN$2026          |
      | cvg.airimport@scangl.com                      | SCAN$2026          |
      | jasan@scangl.com                              | SCAN$2026          |
      | kskaa@scangl.com                              | SCAN$2026          |
      | lax.airexport@scangl.com                      | SCAN$2026          |
      | lax.oceanexport@scangl.com                    | SCAN$2026          |
      | mia.airexport@scangl.com                      | SCAN$2026          |
      | milei@scangl.com                              | SCAN$2026          |
      | mjohn@scangl.com                              | SCAN$2026          |
      | nfish@scangl.com                              | SCAN$2026          |
      | oceanexport@scangl.com                        | SCAN$2026          |
      | oltim@scangl.com                              | SCAN$2026          |
      | ord.oceanexport@scangl.com                    | SCAN$2026          |
      | phx.dom@scangl.com                            | SCAN$2026          |
      | rmora@scangl.com                              | SCAN$2026          |
      | slope@scangl.com                              | SCAN$2026          |
      | vgome@scangl.com                              | SCAN$2026          |
      | wbarr@scangl.com                              | SCAN$2026          |
      | henrymei@scanwell.com                         | SCANWELL$2026      |
      | winsitan@scanwell.com                         | SCANWELL$2026      |
      | adryan.mccauley@maersk.com                    | SENATOR$2026       |
      | alcl_airimport.atl@maersk.com                 | SENATOR$2026       |
      | daniel.richardson@maersk.com                  | SENATOR$2026       |
      | gsp.imp.ocfo@maersk.com                       | SENATOR$2026       |
      | hannah.headley@maersk.com                     | SENATOR$2026       |
      | jennifer.olson@maersk.com                     | SENATOR$2026       |
      | lax.bmw.import_alcl@maersk.com                | SENATOR$2026       |
      | lekisha.howell@maersk.com                     | SENATOR$2026       |
      | regina.grijalva@maersk.com                    | SENATOR$2026       |
      | sandra.ousley@atl.senator-international.com   | SENATOR$2026       |
      | sandra.ousley@maersk.com                      | SENATOR$2026       |
      | sandra.schuch@lax.senator-international.com   | SENATOR$2026       |
      | shannon.mallard@lns.maersk.com                | SENATOR$2026       |
      | william.r@lns.maersk.com                      | SENATOR$2026       |
      | yolanda.marshall@maersk.com                   | SENATOR$2026       |
      | ses-nyc@usa.com                               | SES$2026           |
      | cs@sfsystems.net                              | SF$2026            |
      | export@sfsystems.net                          | SF$2026            |
      | import@sfsystems.net                          | SF$2026            |
      | import2@sfsystems.net                         | SF$2026            |
      | op@sfsystems.net                              | SF$2026            |
      | gerald@shinexpress.com                        | SHINE$2026         |
      | julio@shinexpress.com                         | SHINE$2026         |
      | jlano@shiptechintl.com                        | SHIPTECH$2026      |
      | mnuguid@shiptechintl.com                      | SHIPTECH$2026      |
      | nwagner@shiptechintl.com                      | SHIPTECH$2026      |
      | zsmith@shiptechintl.com                       | SHIPTECH$2026      |
      | ops2@simpleforwarding.com                     | SIMPLE$2026        |
      | karthi@skyferlogistic.com                     | SKYFER$2026        |
      | krystinaz@skyferlogistic.com                  | SKYFER$2026        |
      | richardf@skyferlogistic.com                   | SKYFER$2026        |
      | syed@skyferlogistic.com                       | SKYFER$2026        |
      | vishnum@skyferlogistic.com                    | SKYFER$2026        |
      | airfreight@sladeshipping.com                  | SLADE$2026         |
      | nicol@sladeshipping.com                       | SLADE$2026         |
      | ops@sliglobal.com                             | SLI$2026           |
      | rickyt@sobelnet.com                           | SOBEL$2026         |
      | rocky.shi@sonicainternational.com             | SONICA$2026        |
      | soey.he@sonicainternational.com               | SONICA$2026        |
      | stephanie.cao@sonicainternational.com         | SONICA$2026        |
      | tony.sanrueng@sonicainternational.com         | SONICA$2026        |
      | ord-oceanimport@speedmark.com                 | SPEEDMARK$2026     |
      | air.export@spirit-ord.com                     | SPIRIT$2026        |
      | import@spirit-ord.com                         | SPIRIT$2026        |
      | bosco@sunexp-ny.com                           | SUN$2026           |
      | bookings@supfrt.com                           | SUPERIOR$2026      |
      | synforceop@synforceinc.com                    | SYNFORCE$2026      |
      | leah.atwater@tazmanian.com                    | TAZMANIAN$2026     |
      | rodolfo.rodriguez@tazmanian.com               | TAZMANIAN$2026     |
      | travus.mcdonald@tazmanian.com                 | TAZMANIAN$2026     |
      | atlprimus@teamww.com                          | TEAM$2026          |
      | cltalerts@teamww.com                          | TEAM$2026          |
      | teambna@teamww.com                            | TEAM$2026          |
      | teambwi@teamww.com                            | TEAM$2026          |
      | teamcvg.intl@teamww.com                       | TEAM$2026          |
      | teamcvg@teamww.com                            | TEAM$2026          |
      | teamcvgintl@teamww.com                        | TEAM$2026          |
      | teamdfw@teamww.com                            | TEAM$2026          |
      | teamdtw@teamww.com                            | TEAM$2026          |
      | teamewr@teamww.com                            | TEAM$2026          |
      | teamgso@teamww.com                            | TEAM$2026          |
      | teamlit@teamww.com                            | TEAM$2026          |
      | teammci@teamww.com                            | TEAM$2026          |
      | teamnsc@teamww.com                            | TEAM$2026          |
      | teampit@teamww.com                            | TEAM$2026          |
      | teamsan@teamww.com                            | TEAM$2026          |
      | teamsfo@teamww.com                            | TEAM$2026          |
      | teamslc@teamww.com                            | TEAM$2026          |
      | teamtul@teamww.com                            | TEAM$2026          |
      | amy.chen@tollgroup.com                        | TOLL$2026          |
      | anawake.ray@tollgroup.com                     | TOLL$2026          |
      | anny.wong@tollgroup.com                       | TOLL$2026          |
      | chen.smith@tollgroup.com                      | TOLL$2026          |
      | dawid.augustyn@tollgroup.com                  | TOLL$2026          |
      | domesticusa@tollgroup.com                     | TOLL$2026          |
      | donnie.howard@tollgroup.com                   | TOLL$2026          |
      | hyman.kunkel@tollgroup.com                    | TOLL$2026          |
      | jaqueline.magana@tollgroup.com                | TOLL$2026          |
      | joani.devaney@tollgroup.com                   | TOLL$2026          |
      | julie.sun@tollgroup.com                       | TOLL$2026          |
      | kevin.gallagher@tollgroup.com                 | TOLL$2026          |
      | menecka.chapman@tollgroup.com                 | TOLL$2026          |
      | oscar.perez@tollgroup.com                     | TOLL$2026          |
      | shanqin.zhang@tollgroup.com                   | TOLL$2026          |
      | shogo.hayashida@tollgroup.com                 | TOLL$2026          |
      | tabitha.romaniuk@tollgroup.com                | TOLL$2026          |
      | yolisa.azuero@tollgroup.com                   | TOLL$2026          |
      | yonawattie.khan@tollgroup.com                 | TOLL$2026          |
      | phil.mcinerney@trancoglobal.com               | TRANCO$2026        |
      | exportdtw1@trans-overseas.com                 | TRANS$2026         |
      | logistics@trans-overseas.com                  | TRANS$2026         |
      | aivy@transatl.com                             | TRANSATLANTIC$2026 |
      | alejandra.beltran@transpotrade.com            | TRANSPOTRADE$2026  |
      | geva.arnon@transpotrade.com                   | TRANSPOTRADE$2026  |
      | mahmed@transpotrade.com                       | TRANSPOTRADE$2026  |
      | ogerussi@transpotrade.com                     | TRANSPOTRADE$2026  |
      | paul.ahmed@transpotrade.com                   | TRANSPOTRADE$2026  |
      | chiex@ufreight.com                            | U-FREIGHT$2026     |
      | chiim@ufreight.com                            | U-FREIGHT$2026     |
      | chilg@ufreight.com                            | U-FREIGHT$2026     |
      | chistaff@ufreight.com                         | U-FREIGHT$2026     |
      | laxim@ufreight.com                            | U-FREIGHT$2026     |
      | vincehomes@ufreight.com                       | U-FREIGHT$2026     |
      | a.alas@unique-usa.com                         | UNIQUE$2026        |
      | a.kasten@unique-usa.com                       | UNIQUE$2026        |
      | a.mahabir@unique-usa.com                      | UNIQUE$2026        |
      | airexportops@unique-usa.com                   | UNIQUE$2026        |
      | airimports.lax@unique-usa.com                 | UNIQUE$2026        |
      | andrew.mahabir.nyc@unique-logistics.com       | UNIQUE$2026        |
      | d.arcana@unique-usa.com                       | UNIQUE$2026        |
      | d.chuong@unique-usa.com                       | UNIQUE$2026        |
      | diego.arcana@dpworld.com                      | UNIQUE$2026        |
      | h.corraya@unique-usa.com                      | UNIQUE$2026        |
      | hilary.corraya.nyc@unique-logistics.com       | UNIQUE$2026        |
      | j.budd@unique-usa.com                         | UNIQUE$2026        |
      | j.liang@unique-usa.com                        | UNIQUE$2026        |
      | j.moore@unique-usa.com                        | UNIQUE$2026        |
      | j.osorto@unique-usa.com                       | UNIQUE$2026        |
      | k.mahabir@unique-usa.com                      | UNIQUE$2026        |
      | kumar.mahabir@dpworld.com                     | UNIQUE$2026        |
      | m.ng@unique-usa.com                           | UNIQUE$2026        |
      | mike.ng@dpworld.com                           | UNIQUE$2026        |
      | n.bissaul@unique-usa.com                      | UNIQUE$2026        |
      | p.gray@unique-usa.com                         | UNIQUE$2026        |
      | patricia.gray@dpwamr.com                      | UNIQUE$2026        |
      | patricia.gray@dpworld.com                     | UNIQUE$2026        |
      | patricia.gray@unique-usa.com                  | UNIQUE$2026        |
      | sumera.bakhrani@dpworld.com                   | UNIQUE$2026        |
      | t.orillion@unique-usa.com                     | UNIQUE$2026        |
      | ksullivan@homeshipping.com                    | UNIVERSAL$2026     |
      | alex@ufschicago.com                           | UNIVERSAL$2026     |
      | elizabeth@ufschicago.com                      | UNIVERSAL$2026     |
      | rickh@ufschicago.com                          | UNIVERSAL$2026     |
      | alex.slover@ufschicago.com                    | UNIVERSAL$2026     |
      | universal@universallogistics.net              | UNIVERSAL$2026     |
      | erik.universal@outlook.com                    | UNIVERSAL$2026     |
      | chioc@ufreight.com                            | U-OCEAN$2026       |
      | laximocim@ufreight.com                        | U-OCEAN$2026       |
      | ord@uscom.net                                 | US$2026            |
      | c.fletcher@utcoverseas.com                    | UTC$2026           |
      | miami@utcoverseas.com                         | UTC$2026           |
      | r.carrasquillo@utcoverseas.com                | UTC$2026           |
      | ashley@utulogistics.com                       | UTU$2026           |
      | cecil.k@utulogistics.com                      | UTU$2026           |
      | chloe.k@utulogistics.com                      | UTU$2026           |
      | john.l@utulogistics.com                       | UTU$2026           |
      | oog@utulogistics.com                          | UTU$2026           |
      | yoon.k@utulogistics.com                       | UTU$2026           |
      | erica.im@shipuwl.com                          | UWL$2026           |
      | chiair@shipuwl.com                            | UWL$2026           |
      | air@vlogisticschi.com                         | V$2026             |
      | ocean@vlogisticschi.com                       | V$2026             |
      | neillim@webtransusa.com                       | WEBTRANS$2026      |
      | dpetito@westforwarding.com                    | WEST$2026          |
      | dtracz@westforwarding.com                     | WEST$2026          |
      | dweaver@westforwarding.com                    | WEST$2026          |
      | kbiewer@westforwarding.com                    | WEST$2026          |
      | timzhang@winuslogistics.com                   | WINUS$2026         |
      | op-air@onedreamworks.net                      | WINUS$2026         |
      | ord@onedreamworks.net                         | WINUS$2026         |
      | op6@onedreamworks.net                         | WINUS$2026         |
      | anny.tsai@worldway.us                         | WORLD$2026         |
      | jessy.chen@worldway.us                        | WORLD$2026         |
      | tien.tran@worldwidelogistics.com              | WORLDWIDE$2026     |
      | lmanzano@wwllmail.com                         | WORLDWIDE$2026     |
      | skuzak@wwllmail.com                           | WORLDWIDE$2026     |
      | rwilliams@worldwidelp.com                     | WORLDWIDE$2026     |
      | tbudoff@worldwidelp.com                       | WORLDWIDE$2026     |
      | wt4billing@gmail.com                          | WT$2026            |
      | wtcargofcl@gmail.com                          | WT$2026            |
      | ord@xchange360.com                            | XCHANGE$2026       |